spring:
  config:
    activate:
      on-profile: local
  output.ansi.enabled: ALWAYS

datasource:
  order:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/order
      username: root
      password: root
      pool-name: HikariPool-item-master
      maximum-pool-size: 2
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/order
      username: root
      password: root
      pool-name: HikariPool-item-slave
      maximum-pool-size: 2

product.api.url: http://localhost:8082

server.port: 9090